### ISSUE TITLE
How do I suggest an article?

### ISSUE THREAD

**Issue by avinassh** [knoldus/rust-times#77]
Helooo! I wrote an article about inserting lots of rows in SQLite using Rust. Here is the link - https://avi.im/blag/2021/fast-sqlite-inserts/

I was hoping if you could consider this link to be included in the news letter

**Comment by ankit-mogha** [comment]
Hello, @avinassh we are really sorry that we missed your blog next time will definitely include your new blogs in our upcoming releases. We are closing this issue for now, and feel free to create a new issue for your blogs.
